itkdev_openid_connect:
    openid_provider_options:
        configuration_url: '%env(CONFIGURATION_URL)'
        client_id: '%env(CLIENT_ID)'
        client_secret: '%env(CLIENT_SECRET)'
        cache_path: 'cache.app'
        callback_uri: '%env(CALLBACK_URI)'
    cli_login_options:
        cli_redirect: '%env(CLI_REDIRECT)'

