# itk-version: 3.0.0
version: "3"

services:
  phpfpm:
<<<<<<< Updated upstream
    image: itkdev/php8.0-fpm:alpine
    restart: unless-stopped
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=128M
      - COMPOSER_VERSION=2
    volumes:
      - .:/app
=======
    depends_on:
      - redis
>>>>>>> Stashed changes

  nginx:
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
      - engine

  engine:
    image: node:14
    restart: unless-stopped
    networks:
      - app
<<<<<<< Updated upstream
=======
      - frontend
>>>>>>> Stashed changes
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./engine:/app
    command: npm run prod

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.1
    restart: unless-stopped
    networks:
      - app
    volumes:
      - ./.docker/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./.docker/jvm.options:/usr/share/logstash/config/jvm.options:ro
      - .docker/pipeline:/usr/share/logstash/pipeline:ro

  redis:
    image: 'redis:5'
    restart: unless-stopped
    networks:
      - app

  memcached:
    image: 'memcached:latest'
    restart: unless-stopped
    networks:
      - app
    environment:
      - MEMCACHED_CACHE_SIZE=64
