on: pull_request
name: Review
jobs:
    js-coding-standards:
        name: JS coding standards
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - name: install
              working-directory: engine
              run: npm install
            - name: JS coding standards
              working-directory: engine
              run: npm run check-coding-standards

    js-engine-tests:
        name: JS engine tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   uses: actions/setup-node@v1
                with:
                    node-version: '10.x'
            -   name: install
                working-directory: engine
                run: npm run test-install
            -   name: JS tests
                working-directory: engine
                run: npm test
