on: pull_request
name: Review
jobs:
    engine-coding-standards:
        name: Engine coding standards
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: install
              working-directory: engine
              run: npm install
            - name: JS coding standards
              working-directory: engine
              run: npm run check-coding-standards

    engine-tests:
        name: JS engine tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   uses: actions/setup-node@v1
                with:
                    node-version: '14.x'
            -   name: install plugins
                working-directory: engine
                run: npm run test-install
            -   name: install
                working-directory: engine
                run: npm install
            -   name: JS tests
                working-directory: engine
                run: npm test

    frontend-tests:
        name: Frontend tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: install
              run: npm install
            - name: Run tests
              run: npm run test-ci
