on: pull_request
name: Review
jobs:
    js-coding-standards:
        name: JS coding standards (PHP ${{ matrix.php }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.3']
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - name: install
              working-directory: engine
              run: yarn install
            - name: JS coding standards
              working-directory: engine
              run: yarn check-coding-standards

    frontend-testing:
        name: Frontend tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: install
              working-directory: frontend
              run: yarn install
            - name: Run tests
              working-directory: frontend
              run: yarn test-ci
