on: pull_request
name: Review
jobs:
    js-coding-standards:
        name: JS coding standards (PHP ${{ matrix.php }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.3']
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - name: install
              run: yarn install
            - name: JS coding standards
              run: yarn check-coding-standards
